version: '3.3'

services:
  webserver:
    image: nginx:alpine
    container_name: checker-webserver
    restart: unless-stopped
    volumes:
      - ./main:/application
      - ./docker/webserver:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    links:
      - phoenix
      - php-fpm
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: checker-php-fpm
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ./main:/application
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  phoenix:
    build: docker/phoenix
    container_name: checker-phoenix
    restart: unless-stopped
    volumes:
      - ./phoenix:/application
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  echo-server:
    build: docker/echo-server
    container_name: checker-echo-server
    volumes:
      - ./main:/application
      - ./docker/echo-server/config.json:/application/laravel-echo-server.json
    restart: unless-stopped
    ports:
      - ${ECHO_SERVER_PORT}:6001
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: bitnami/redis:latest
    container_name: checker-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  queue:
    build: docker/queue
    container_name: checker-queue
    restart: unless-stopped
    volumes:
      - ./main:/application
      - ./docker/queue/php-ini-overrides.ini:/usr/local/etc/php/php.ini
      - ./docker/queue/supervisord.conf:/etc/supervisor/conf.d/application.conf
    environment:
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql

  scheduler:
    build: docker/scheduler
    container_name: checker-scheduler
    command: sh /usr/bin/entrypoint.sh
    restart: unless-stopped
    volumes:
      - ./main:/application
      - ./docker/scheduler/entrypoint.sh:/usr/bin/entrypoint.sh
      - ./docker/scheduler/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:latest
    container_name: checker-mysql
    restart: unless-stopped
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - TZ=${MYSQL_TIME_ZONE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
